name: kerra-app
services:
  - name: web
    source_dir: /
    github:
      repo: your-username/kerra
      branch: main
    run_command: node .output/server/index.mjs
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: npm ci && npm run build
    http_port: 3000
    health_check:
      http_path: /api/health
    envs:
      - key: NODE_ENV
        value: production
      - key: API_SECRET
        type: SECRET
      - key: DATABASE_URL
        type: SECRET
